## YAML Template.
---
default:
  http_metas:
    content-type: text/html

  metas:
    title:        Torneos
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [EstiloTorneo, EstiloIndex]

  javascripts:    []

  has_layout:     true
  layout:         layout