## YAML Template.
---
default:
  http_metas:
    content-type: text/html

  metas:
    title:        Alquileres
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [EstiloAlquiler]

  javascripts:    []

  has_layout:     true
  layout:         layout