# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, EstiloIndex.css, "ui-lightness/jquery-ui-1.8.16.custom.css"]

  javascripts:    ["jquery.min.js", "jquery.ui.datepicker-es.js", "jquery-ui-1.8.16.custom.min.js", "mi_jquery.validate.js", "vanadium_es.js", "funciones.js"]

  has_layout:     true
  layout:         layout
